jobs:
  include:
    - language: go
      go: "1.14"
      services:
        - docker
      env:
        # MEDCO_DB_NUMBER is the number of databases used in the profile that will be tested
        - MEDCO_DB_NUMBER=9
        - MEDCO_DB_HOST=localhost
        - MEDCO_DB_PORT=5432
        - MEDCO_DB_USER=postgres
        - MEDCO_DB_PASSWORD=postgres
        - MEDCO_DB_NAME=postgres
        - MEDCO_USER_USERNAME=test
        - MEDCO_USER_PASSWORD=test
      before_install:
        - cd ~/build/ldsec/medco/test/data
        - bash download.sh
        - cd ~/build/ldsec/medco/deployments/dev-local-3nodes
        - docker-compose -f docker-compose.yml -f docker-compose.tools.yml build
      install:
        - docker-compose up -d
        - bash ~/build/ldsec/medco/test/wait_for_startup.sh $MEDCO_DB_NUMBER $MEDCO_DB_HOST $MEDCO_DB_PORT $MEDCO_DB_USER $MEDCO_DB_PASSWORD $MEDCO_DB_NAME
        - docker-compose -f docker-compose.tools.yml run medco-loader-srv0 v0 --ont_clinical /data/genomic/tcga_cbio/8_clinical_data.csv --sen /data/genomic/sensitive.txt --ont_genomic /data/genomic/tcga_cbio/8_mutation_data.csv --clinical /data/genomic/tcga_cbio/8_clinical_data.csv --genomic /data/genomic/tcga_cbio/8_mutation_data.csv --output /data/
        - docker-compose -f docker-compose.tools.yml run medco-loader-srv1 v0 --ont_clinical /data/genomic/tcga_cbio/8_clinical_data.csv --sen /data/genomic/sensitive.txt --ont_genomic /data/genomic/tcga_cbio/8_mutation_data.csv --clinical /data/genomic/tcga_cbio/8_clinical_data.csv --genomic /data/genomic/tcga_cbio/8_mutation_data.csv --output /data/
        - docker-compose -f docker-compose.tools.yml run medco-loader-srv2 v0 --ont_clinical /data/genomic/tcga_cbio/8_clinical_data.csv --sen /data/genomic/sensitive.txt --ont_genomic /data/genomic/tcga_cbio/8_mutation_data.csv --clinical /data/genomic/tcga_cbio/8_clinical_data.csv --genomic /data/genomic/tcga_cbio/8_mutation_data.csv --output /data/
      script:
        - bash ~/build/ldsec/medco/test/test_e2e.sh $MEDCO_USER_USERNAME $MEDCO_USER_PASSWORD

    - language: go
      before_install:
        - cd ~/build/ldsec/medco/data
        - bash download.sh
      install:
        - cd ~/build/ldsec/medco
        - go get -t ./...
        - go get github.com/mattn/goveralls
      script:
        - make test
      after_success:
        - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email: false
