version: '3.5'
services:
  medco-connector:
    image: medco/medco-connector:dev
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - "1999"
    environment:
      - PICSURE2_INTERNAL_TOKEN=asdasd-456465-asdasd-x
      - I2B2_HIVE_URL=http://i2b2:8080/i2b2/services
      - I2B2_LOGIN_DOMAIN=i2b2medco
      - I2B2_LOGIN_PROJECT=MedCo
      - I2B2_LOGIN_USER=e2etest
      - I2B2_LOGIN_PASSWORD=e2etest
      - LOG_LEVEL=5
